GET http://localhost:8080/api/v1/chatrooms/
Content-Type: application/json
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTQ0ODQ5MTF9.e_zNd7zpfz6omqtfDgSPcNkLQNM-cS5A5Wpj3t0-ctI
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTUwODg4MTF9.aLCyWPH059wASVSewf4sfNI_Q1M4SnGjAyB7kS7Io18

###
GET http://localhost:8080/api/v1/chatrooms/664473ddc9d98f866a6dc836
Content-Type: application/json
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTQ0ODQ5MTF9.e_zNd7zpfz6omqtfDgSPcNkLQNM-cS5A5Wpj3t0-ctI
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTUwODg4MTF9.aLCyWPH059wASVSewf4sfNI_Q1M4SnGjAyB7kS7Io18

###

POST http://localhost:8080/api/v1/chatrooms
Content-Type: application/json
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTQ0ODQ5MTF9.e_zNd7zpfz6omqtfDgSPcNkLQNM-cS5A5Wpj3t0-ctI
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTUwODg4MTF9.aLCyWPH059wASVSewf4sfNI_Q1M4SnGjAyB7kS7Io18

{
    "chatroomName": "TESTER",
    "chatroomUserCreatorId": "1",
    "color": "000",
    "members": [],
    "messages": []
}

###

PUT http://localhost:8080/api/v1/chatrooms/664237a0361e6b5e805173cd
Content-Type: application/json
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTQ0ODQ5MTF9.e_zNd7zpfz6omqtfDgSPcNkLQNM-cS5A5Wpj3t0-ctI
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzAwNjAzMDczOTM3N2E5NDgyNmJmMyIsInVzZXJuYW1lIjoiam9uZG9lIiwiaWF0IjoxNzE0NDg0MDExLCJleHAiOjE3MTUwODg4MTF9.aLCyWPH059wASVSewf4sfNI_Q1M4SnGjAyB7kS7Io18

{
    "chatroomName": "NEW NAME",
    "chatroomUserCreatorId": "1",
    "color": "000",
    "members": [],
    "messages": []
}

###

DELETE http://localhost:8080/api/v1/chatrooms/664289e417a6158b0c9437ba